"""
This type stub file was generated by pyright.
"""

import threading

class StoppableThread(threading.Thread):
    def get_id(self): # -> None:
        ...
    
    def kill(self): # -> None:
        ...
    


