"""
This type stub file was generated by pyright.
"""

import typing
from dash.development.base_component import Component, ComponentType, _explicitize_args

class BaseLayer(Component):
    """A BaseLayer component.
BaseLayer is a wrapper of LayersControl.BaseLayer in react-leaflet. It takes similar properties to its react-leaflet counterpart.

Keyword arguments:

- children (a list of or a singular dash component, string or number; optional):
    Children [MUTABLE].

- id (string; optional):
    Unique ID to identify this component in Dash callbacks.

- checked (boolean; optional):
    If True, the layer is shown, otherwise it's hidden. [MUTABLE].

- loading_state (dict; optional):
    Dash loading state information.

- name (boolean; required):
    Name of the layer, used for the label in the LayersControl."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    @_explicitize_args
    def __init__(self, children: typing.Optional[typing.Union[str, int, float, ComponentType, typing.Sequence[typing.Union[str, int, float, ComponentType]]]] = ..., name: typing.Optional[bool] = ..., checked: typing.Optional[bool] = ..., id: typing.Optional[typing.Union[str, dict]] = ..., loading_state: typing.Optional[dict] = ..., **kwargs) -> None:
        ...
    


