"""
This type stub file was generated by pyright.
"""

def categorical_colorbar(*args, categories, colorscale, **kwargs): # -> Colorbar:
    ...

def dicts_to_geojson(dicts, lat=..., lon=...): # -> dict[str, str | list[Any]]:
    ...

def geojson_to_geobuf(geojson): # -> str:
    ...

