"""
This type stub file was generated by pyright.
"""

import typing
from dash.development.base_component import Component, _explicitize_args

class GestureHandling(Component):
    """A GestureHandling component.
GestureHandling is a light wrapper of https://github.com/elmarquis/Leaflet.GestureHandling

Keyword arguments:

- id (string; optional):
    Unique ID to identify this component in Dash callbacks.

- loading_state (dict; optional):
    Dash loading state information."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    @_explicitize_args
    def __init__(self, id: typing.Optional[typing.Union[str, dict]] = ..., loading_state: typing.Optional[dict] = ..., **kwargs) -> None:
        ...
    


