"""
This type stub file was generated by pyright.
"""

import typing
from dash.development.base_component import Component, ComponentType, _explicitize_args

class Pane(Component):
    """A Pane component.
Panes are DOM elements used to control the ordering of layers on the map.

Keyword arguments:

- children (a list of or a singular dash component, string or number; optional):
    Children [MUTABLE].

- id (string; optional):
    Unique ID to identify this component in Dash callbacks.

- className (string; optional):
    CSS class(es).

- loading_state (dict; optional):
    Dash loading state information.

- name (string; required):
    The name must be unique to the pane and different from the default
    Leaflet pane names.

- pane (string; optional):
    Map pane where the layer will be added."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    @_explicitize_args
    def __init__(self, children: typing.Optional[typing.Union[str, int, float, ComponentType, typing.Sequence[typing.Union[str, int, float, ComponentType]]]] = ..., name: typing.Optional[str] = ..., className: typing.Optional[str] = ..., pane: typing.Optional[str] = ..., style: typing.Optional[typing.Any] = ..., id: typing.Optional[typing.Union[str, dict]] = ..., loading_state: typing.Optional[dict] = ..., **kwargs) -> None:
        ...
    


