"""
This type stub file was generated by pyright.
"""

import typing
import numbers
from dash.development.base_component import Component, ComponentType, _explicitize_args

class Badge(Component):
    """A Badge component.
Badges can be used to add counts or labels to other components.

Keyword arguments:

- children (a list of or a singular dash component, string or number; optional):
    The children of the Badge.

- id (string; optional):
    The ID of the Badge.

- color (string; default 'secondary'):
    Badge color, options: primary, secondary, success, info, warning,
    danger, link or any valid CSS color of your choice (e.g. a hex
    code, a decimal code or a CSS color name).  Default: secondary.

- text_color (string; optional):
    Set the color of the text to one of the Bootstrap contextual
    colors.  Options: primary, secondary, success, info, warning,
    danger, light or dark.

- n_clicks (number; default 0):
    The number of times the Badge has been clicked.

- href (string; optional):
    A URL to link to when the Badge is clicked.

- external_link (boolean; optional):
    If True, clicking on the Badge will behave like a hyperlink. If
    False, the Badge will behave like a dcc.Link component, and can be
    used in conjunction with dcc.Location for navigation within a Dash
    app.

- pill (boolean; optional):
    Make badge \"pill\" shaped (rounded ends, like a pill). Default:
    False.

- class_name (string; optional):
    Additional CSS classes to apply to the Badge.

- tag (string; optional):
    HTML tag to use for the Badge. Default: span.

- target (string; optional):
    Target attribute to pass on to the link. Only applies to external
    links.

- title (string; optional):
    Sets the title attribute of the underlying HTML button.

- key (string; optional):
    A unique identifier for the component, used to improve performance
    by React.js while rendering components  See
    https://react.dev/learn/rendering-lists#why-does-react-need-keys
    for more info.

- className (string; optional):
    **DEPRECATED** Use `class_name` instead.  Additional CSS classes
    to apply to the Badge."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    @_explicitize_args
    def __init__(self, children: typing.Optional[typing.Union[str, int, float, ComponentType, typing.Sequence[typing.Union[str, int, float, ComponentType]]]] = ..., id: typing.Optional[typing.Union[str, dict]] = ..., *, color: typing.Optional[str] = ..., text_color: typing.Optional[str] = ..., n_clicks: typing.Optional[typing.Union[int, float, numbers.Number]] = ..., href: typing.Optional[str] = ..., external_link: typing.Optional[bool] = ..., pill: typing.Optional[bool] = ..., style: typing.Optional[typing.Any] = ..., class_name: typing.Optional[str] = ..., tag: typing.Optional[str] = ..., target: typing.Optional[str] = ..., title: typing.Optional[str] = ..., key: typing.Optional[str] = ..., className: typing.Optional[str] = ..., **kwargs) -> None:
        ...
    


