"""
This type stub file was generated by pyright.
"""

import typing
from typing_extensions import NotRequired, TypedDict
from dash.development.base_component import Component, _explicitize_args

class Breadcrumb(Component):
    """A Breadcrumb component.
Use breadcrumbs to create a navigation breadcrumb in your app.

Keyword arguments:

- id (string; optional):
    The ID of the Breadcrumb.

- items (list of dicts; optional):
    The details of the items to render inside of this component.

    `items` is a list of dicts with keys:

    - label (string; optional):
        The label to display inside the breadcrumbs.

    - href (string; optional):
        URL of the resource to link to.

    - active (boolean; optional):
        If True, the item will be displayed as active.

    - external_link (boolean; optional):
        If True, clicking on the item will behave like a hyperlink. If
        False, the item will behave like a dcc.Link component, and can
        be used in conjunction with dcc.Location for navigation within
        a Dash app.

    - target (string; optional):
        Target attribute to pass on to the link. Only applies to
        external links.

    - title (string; optional):
        Title attribute for the inner anchor element.

- item_style (dict; optional):
    Additional inline CSS styles to apply to each item.

- class_name (string; optional):
    Additional CSS classes to apply to the Breadcrumb.

- item_class_name (string; optional):
    Additional CSS classes to apply to each item.

- key (string; optional):
    A unique identifier for the component, used to improve performance
    by React.js while rendering components  See
    https://react.dev/learn/rendering-lists#why-does-react-need-keys
    for more info.

- className (string; optional):
    **DEPRECATED** - Use class_name instead.  Additional CSS classes
    to apply to the Breadcrumb.

- itemClassName (string; optional):
    **DEPRECATED** - use item_class_name instead.  Additional CSS
    classes to apply to each item.

- tag (dict; optional):
    HTML tag to use for the outer breadcrumb component. Default:
    \"nav\"."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    Items = TypedDict("Items", { "label": NotRequired[str],"href": NotRequired[str],"active": NotRequired[bool],"external_link": NotRequired[bool],"target": NotRequired[str],"title": NotRequired[str] })
    @_explicitize_args
    def __init__(self, id: typing.Optional[typing.Union[str, dict]] = ..., *, items: typing.Optional[typing.Sequence[Items]] = ..., style: typing.Optional[typing.Any] = ..., item_style: typing.Optional[dict] = ..., class_name: typing.Optional[str] = ..., item_class_name: typing.Optional[str] = ..., key: typing.Optional[str] = ..., className: typing.Optional[str] = ..., itemClassName: typing.Optional[str] = ..., tag: typing.Optional[dict] = ..., **kwargs) -> None:
        ...
    


