"""
This type stub file was generated by pyright.
"""

import typing
from dash.development.base_component import Component, ComponentType, _explicitize_args

class CardImgOverlay(Component):
    """A CardImgOverlay component.
Use CardImgOverlay to turn an image into the background of your card and add text on
top of it.

Keyword arguments:

- children (a list of or a singular dash component, string or number; optional):
    The children of this CardImgOverlay.

- id (string; optional):
    The ID of the CardImgOverlay.

- class_name (string; optional):
    Additional CSS classes to apply to the CardImgOverlay.

- tag (string; optional):
    HTML tag to use for the card image overlay, default: div.

- key (string; optional):
    A unique identifier for the component, used to improve performance
    by React.js while rendering components  See
    https://react.dev/learn/rendering-lists#why-does-react-need-keys
    for more info.

- className (string; optional):
    **DEPRECATED** Use `class_name` instead.  Additional CSS classes
    to apply to the CardImgOverlay."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    @_explicitize_args
    def __init__(self, children: typing.Optional[typing.Union[str, int, float, ComponentType, typing.Sequence[typing.Union[str, int, float, ComponentType]]]] = ..., id: typing.Optional[typing.Union[str, dict]] = ..., *, style: typing.Optional[typing.Any] = ..., class_name: typing.Optional[str] = ..., tag: typing.Optional[str] = ..., key: typing.Optional[str] = ..., className: typing.Optional[str] = ..., **kwargs) -> None:
        ...
    


