"""
This type stub file was generated by pyright.
"""

import typing
from dash.development.base_component import Component, ComponentType, _explicitize_args

class Card(Component):
    """A Card component.
Component for creating Bootstrap cards. Use in conjunction with CardBody, CardImg,
CardLink, CardHeader and CardFooter. Can also be used in conjunction with
CardColumns, CardDeck, CardGroup for different layout options.

Keyword arguments:

- children (a list of or a singular dash component, string or number; optional):
    The children of this Card.

- id (string; optional):
    The ID of the Card.

- color (string; optional):
    Card color, options: primary, secondary, success, info, warning,
    danger, light, dark or any valid CSS color of your choice (e.g. a
    hex code, a decimal code or a CSS color name).  Default is light.

- body (boolean; optional):
    Apply the `card-body` class to the card, so that there is no need
    to also include a CardBody component in the children of this Card.
    Default: False.

- outline (boolean; optional):
    Apply color styling to just the border of the Card.

- inverse (boolean; optional):
    Invert text colours for use with a darker background.

- class_name (string; optional):
    Additional CSS classes to apply to the Card.

- key (string; optional):
    A unique identifier for the component, used to improve performance
    by React.js while rendering components  See
    https://react.dev/learn/rendering-lists#why-does-react-need-keys
    for more info.

- className (string; optional):
    **DEPRECATED** Use `class_name` instead.  Additional CSS classes
    to apply to the Card."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    @_explicitize_args
    def __init__(self, children: typing.Optional[typing.Union[str, int, float, ComponentType, typing.Sequence[typing.Union[str, int, float, ComponentType]]]] = ..., id: typing.Optional[typing.Union[str, dict]] = ..., *, color: typing.Optional[str] = ..., body: typing.Optional[bool] = ..., outline: typing.Optional[bool] = ..., inverse: typing.Optional[bool] = ..., style: typing.Optional[typing.Any] = ..., class_name: typing.Optional[str] = ..., key: typing.Optional[str] = ..., className: typing.Optional[str] = ..., **kwargs) -> None:
        ...
    


