"""
This type stub file was generated by pyright.
"""

import typing
import numbers
from typing_extensions import Literal
from dash.development.base_component import Component, ComponentType, _explicitize_args

class Form(Component):
    """A Form component.
The Form component can be used to organise collections of input components
and apply consistent styling.

Keyword arguments:

- children (a list of or a singular dash component, string or number; optional):
    The children of this Form.

- id (string; optional):
    The ID of the Form.

- n_submit (number; default 0):
    Number of times the form was submitted.

- class_name (string; optional):
    Additional CSS classes to apply to the Form.

- action (string; optional):
    The URI of a program that processes the information submitted via
    the form.

- method (a value equal to: 'GET', 'POST'; optional):
    Defines which HTTP method to use when submitting the form. Can be
    GET (default) or POST.

- prevent_default_on_submit (boolean; default True):
    The form calls preventDefault on submit events. If you want form
    data be posted to the endpoint specified by `action` on submit
    events, set prevent_default_on_submit to False. Defaults to True.

- key (string; optional):
    A unique identifier for the component, used to improve performance
    by React.js while rendering components  See
    https://react.dev/learn/rendering-lists#why-does-react-need-keys
    for more info.

- className (string; optional):
    **DEPRECATED** Use `class_name` instead.  Additional CSS classes
    to apply to the Form."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    @_explicitize_args
    def __init__(self, children: typing.Optional[typing.Union[str, int, float, ComponentType, typing.Sequence[typing.Union[str, int, float, ComponentType]]]] = ..., id: typing.Optional[typing.Union[str, dict]] = ..., *, n_submit: typing.Optional[typing.Union[int, float, numbers.Number]] = ..., style: typing.Optional[typing.Any] = ..., class_name: typing.Optional[str] = ..., action: typing.Optional[str] = ..., method: typing.Optional[Literal["GET", "POST"]] = ..., prevent_default_on_submit: typing.Optional[bool] = ..., key: typing.Optional[str] = ..., className: typing.Optional[str] = ..., **kwargs) -> None:
        ...
    


