"""
This type stub file was generated by pyright.
"""

import typing
from typing_extensions import Literal
from dash.development.base_component import Component, ComponentType, _explicitize_args

class FormFeedback(Component):
    """A FormFeedback component.
The FormFeedback component can be used to provide feedback on input values in a form.
Add the form feedback to your layout and set the `valid` or `invalid` props of the
associated input to toggle visibility.

Keyword arguments:

- children (a list of or a singular dash component, string or number; optional):
    The children of this FormFeedback.

- id (string; optional):
    The ID of the FormFeedback.

- type (a value equal to: 'valid', 'invalid'; optional):
    Either 'valid' or 'invalid'.

- tooltip (boolean; optional):
    Use styled tooltips to display validation feedback.

- class_name (string; optional):
    Additional CSS classes to apply to the FormFeedback.

- key (string; optional):
    A unique identifier for the component, used to improve performance
    by React.js while rendering components  See
    https://react.dev/learn/rendering-lists#why-does-react-need-keys
    for more info.

- className (string; optional):
    **DEPRECATED** Use `class_name` instead.  Additional CSS classes
    to apply to the FormFeedback."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    @_explicitize_args
    def __init__(self, children: typing.Optional[typing.Union[str, int, float, ComponentType, typing.Sequence[typing.Union[str, int, float, ComponentType]]]] = ..., id: typing.Optional[typing.Union[str, dict]] = ..., *, type: typing.Optional[Literal["valid", "invalid"]] = ..., tooltip: typing.Optional[bool] = ..., style: typing.Optional[typing.Any] = ..., class_name: typing.Optional[str] = ..., key: typing.Optional[str] = ..., className: typing.Optional[str] = ..., **kwargs) -> None:
        ...
    


