"""
This type stub file was generated by pyright.
"""

import typing
from typing_extensions import Literal
from dash.development.base_component import Component, ComponentType, _explicitize_args

class Label(Component):
    """A Label component.
A component for adding labels to inputs in forms with added sizing controls.

Keyword arguments:

- children (a list of or a singular dash component, string or number; optional):
    The children of this Label.

- id (string; optional):
    The ID of the Label.

- size (string; optional):
    Set size of label. Options 'sm', 'md' (default) or 'lg'.

- html_for (string; optional):
    Set the `for` attribute of the label to bind it to a particular
    element.

- class_name (string; optional):
    Additional CSS classes to apply to the Label.

- hidden (boolean; optional):
    Hide label from UI, but allow it to be discovered by
    screen-readers.

- check (boolean; optional):
    Set to True when using to label a Checkbox or RadioButton.

- width (optional):
    Specify width of label for use in grid layouts. Accepts the same
    values as the Col component.

- xs (optional):
    Specify label width on extra small screen  Valid arguments are
    boolean, an integer in the range 1-12 inclusive, or a dictionary
    with keys 'offset', 'order', 'size'. See the documentation for
    more details.

- sm (optional):
    Specify label width on a small screen  Valid arguments are
    boolean, an integer in the range 1-12 inclusive, or a dictionary
    with keys 'offset', 'order', 'size'. See the documentation for
    more details.

- md (optional):
    Specify label width on a medium screen  Valid arguments are
    boolean, an integer in the range 1-12 inclusive, or a dictionary
    with keys 'offset', 'order', 'size'. See the documentation for
    more details.

- lg (optional):
    Specify label width on a large screen  Valid arguments are
    boolean, an integer in the range 1-12 inclusive, or a dictionary
    with keys 'offset', 'order', 'size'. See the documentation for
    more details.

- xl (optional):
    Specify label width on an extra large screen  Valid arguments are
    boolean, an integer in the range 1-12 inclusive, or a dictionary
    with keys 'offset', 'order', 'size'. See the documentation for
    more details.

- xxl (optional):
    Specify label width on an extra extra large screen  Valid
    arguments are boolean, an integer in the range 1-12 inclusive, or
    a dictionary with keys 'offset', 'order', 'size'. See the
    documentation for more details.

- align (a value equal to: 'start', 'center', 'end'; default 'center'):
    Set vertical alignment of the label, options: 'start', 'center',
    'end', default: 'center'.

- color (string; optional):
    Text color, options: primary, secondary, success, warning, danger,
    info, muted, light, dark, body, white, black-50, white-50 or any
    valid CSS color of your choice (e.g. a hex code, a decimal code or
    a CSS color name).

- key (string; optional):
    A unique identifier for the component, used to improve performance
    by React.js while rendering components  See
    https://react.dev/learn/rendering-lists#why-does-react-need-keys
    for more info.

- className (string; optional):
    **DEPRECATED** Use `class_name` instead.  Additional CSS classes
    to apply to the Label."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    @_explicitize_args
    def __init__(self, children: typing.Optional[typing.Union[str, int, float, ComponentType, typing.Sequence[typing.Union[str, int, float, ComponentType]]]] = ..., id: typing.Optional[typing.Union[str, dict]] = ..., *, size: typing.Optional[str] = ..., html_for: typing.Optional[str] = ..., style: typing.Optional[typing.Any] = ..., class_name: typing.Optional[str] = ..., hidden: typing.Optional[bool] = ..., check: typing.Optional[bool] = ..., width: typing.Optional[typing.Any] = ..., xs: typing.Optional[typing.Any] = ..., sm: typing.Optional[typing.Any] = ..., md: typing.Optional[typing.Any] = ..., lg: typing.Optional[typing.Any] = ..., xl: typing.Optional[typing.Any] = ..., xxl: typing.Optional[typing.Any] = ..., align: typing.Optional[Literal["start", "center", "end"]] = ..., color: typing.Optional[str] = ..., key: typing.Optional[str] = ..., className: typing.Optional[str] = ..., **kwargs) -> None:
        ...
    


