"""
This type stub file was generated by pyright.
"""

import typing
from dash.development.base_component import Component, ComponentType, _explicitize_args

class ModalHeader(Component):
    """A ModalHeader component.
Add a header to any Modal.

Keyword arguments:

- children (a list of or a singular dash component, string or number; optional):
    The children of this ModalHeader.

- id (string; optional):
    The ID of the ModalHeader.

- close_button (boolean; default True):
    Add a close button to the header that can be used to close the
    modal.

- class_name (string; optional):
    Additional CSS classes to apply to the ModalHeader.

- tag (string; optional):
    HTML tag to use for the ModalHeader, default: div.

- className (string; optional):
    **DEPRECATED** Use `class_name` instead.  Additional CSS classes
    to apply to the ModalHeader."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    @_explicitize_args
    def __init__(self, children: typing.Optional[typing.Union[str, int, float, ComponentType, typing.Sequence[typing.Union[str, int, float, ComponentType]]]] = ..., id: typing.Optional[typing.Union[str, dict]] = ..., *, close_button: typing.Optional[bool] = ..., style: typing.Optional[typing.Any] = ..., class_name: typing.Optional[str] = ..., tag: typing.Optional[str] = ..., className: typing.Optional[str] = ..., **kwargs) -> None:
        ...
    


