"""
This type stub file was generated by pyright.
"""

import typing
import numbers
from dash.development.base_component import Component, ComponentType, _explicitize_args

class NavbarToggler(Component):
    """A NavbarToggler component.
Use this component to create a navbar toggle to show navlinks when the Navbar
collapses on smaller screens.

Keyword arguments:

- children (a list of or a singular dash component, string or number; optional):
    The children of this component.

- id (string; optional):
    The ID of the component.

- n_clicks (number; default 0):
    The number of times the NavbarToggler has been clicked.

- class_name (string; optional):
    Additional CSS classes to apply to the NavbarToggler.

- type (string; optional):
    Toggle type, default: button.

- key (string; optional):
    A unique identifier for the component, used to improve performance
    by React.js while rendering components  See
    https://react.dev/learn/rendering-lists#why-does-react-need-keys
    for more info.

- className (string; optional):
    **DEPRECATED** Use `class_name` instead.  Additional CSS classes
    to apply to the NavbarToggler."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    @_explicitize_args
    def __init__(self, children: typing.Optional[typing.Union[str, int, float, ComponentType, typing.Sequence[typing.Union[str, int, float, ComponentType]]]] = ..., id: typing.Optional[typing.Union[str, dict]] = ..., *, n_clicks: typing.Optional[typing.Union[int, float, numbers.Number]] = ..., style: typing.Optional[typing.Any] = ..., class_name: typing.Optional[str] = ..., type: typing.Optional[str] = ..., key: typing.Optional[str] = ..., className: typing.Optional[str] = ..., **kwargs) -> None:
        ...
    


