"""
This type stub file was generated by pyright.
"""

import typing
from dash.development.base_component import Component, ComponentType, _explicitize_args

class NavbarBrand(Component):
    """A NavbarBrand component.
Call out attention to a brand name or site title within a Navbar.

Keyword arguments:

- children (a list of or a singular dash component, string or number; optional):
    The children of this NavbarBrand.

- id (string; optional):
    The ID of the NavbarBrand.

- external_link (boolean; optional):
    If True, clicking on the NavbarBrand will behave like a hyperlink.
    If False, the NavbarBrand will behave like a dcc.Link component,
    and can be used in conjunction with dcc.Location for navigation
    within a Dash app.

- href (string; optional):
    URL of the linked resource.

- class_name (string; optional):
    Additional CSS classes to apply to the NavbarBrand.

- key (string; optional):
    A unique identifier for the component, used to improve performance
    by React.js while rendering components  See
    https://react.dev/learn/rendering-lists#why-does-react-need-keys
    for more info.

- className (string; optional):
    **DEPRECATED** Use `class_name` instead.  Additional CSS classes
    to apply to the NavbarBrand."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    @_explicitize_args
    def __init__(self, children: typing.Optional[typing.Union[str, int, float, ComponentType, typing.Sequence[typing.Union[str, int, float, ComponentType]]]] = ..., id: typing.Optional[typing.Union[str, dict]] = ..., *, external_link: typing.Optional[bool] = ..., href: typing.Optional[str] = ..., style: typing.Optional[typing.Any] = ..., class_name: typing.Optional[str] = ..., key: typing.Optional[str] = ..., className: typing.Optional[str] = ..., **kwargs) -> None:
        ...
    


