"""
This type stub file was generated by pyright.
"""

import typing
import numbers
from typing_extensions import Literal
from dash.development.base_component import Component, ComponentType, _explicitize_args

class Stack(Component):
    """A Stack component.
Stacks are shorthand helpers that build on top of existing flexbox
utilities to make component layout faster and easier than ever.

Keyword arguments:

- children (a list of or a singular dash component, string or number; optional):
    The children of this Stack.

- id (string; optional):
    The ID of the Stack.

- direction (a value equal to: 'vertical', 'horizontal'; optional):
    Which direction to stack the objects in.

- gap (number; optional):
    Set the spacing between each item (0 - 5).

- class_name (string; optional):
    Additional CSS classes to apply to the Stack.

- key (string; optional):
    A unique identifier for the component, used to improve performance
    by React.js while rendering components  See
    https://react.dev/learn/rendering-lists#why-does-react-need-keys
    for more info.

- className (string; optional):
    **DEPRECATED** Use `class_name` instead.  Additional CSS classes
    to apply to the Stack."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    @_explicitize_args
    def __init__(self, children: typing.Optional[typing.Union[str, int, float, ComponentType, typing.Sequence[typing.Union[str, int, float, ComponentType]]]] = ..., id: typing.Optional[typing.Union[str, dict]] = ..., *, direction: typing.Optional[Literal["vertical", "horizontal"]] = ..., gap: typing.Optional[typing.Union[int, float, numbers.Number]] = ..., style: typing.Optional[typing.Any] = ..., class_name: typing.Optional[str] = ..., key: typing.Optional[str] = ..., className: typing.Optional[str] = ..., **kwargs) -> None:
        ...
    


