"""
This type stub file was generated by pyright.
"""

import typing
from dash.development.base_component import Component, ComponentType, _explicitize_args

class Tab(Component):
    """A Tab component.
Create a single tab. Should be used as a component of Tabs.

Keyword arguments:

- children (a list of or a singular dash component, string or number; optional):
    The children of this Tab.

- id (string; optional):
    The ID of the Tab.

- label (string; optional):
    The tab's label, displayed in the tab itself.

- tab_id (string; optional):
    Optional identifier for tab used for determining which tab is
    visible if not specified, and Tab is being used inside Tabs
    component, the tabId will be set to \"tab-i\" where i is (zero
    indexed) position of tab in list tabs pased to Tabs component.

- disabled (boolean; optional):
    Determines if Tab is disabled or not - defaults to False.

- tab_style (dict; optional):
    Defines CSS styles which will override styles previously set. The
    styles set here apply to the NavItem in the tab.

- active_tab_style (dict; optional):
    Defines CSS styles which will override styles previously set. The
    styles set here apply to the NavItem in the tab when it is active.

- label_style (dict; optional):
    Defines CSS styles which will override styles previously set. The
    styles set here apply to the NavLink in the tab.

- active_label_style (dict; optional):
    Defines CSS styles which will override styles previously set. The
    styles set here apply to the NavLink in the tab when it is active.

- class_name (string; optional):
    Additional CSS classes to apply to the Tabs.

- tab_class_name (string; optional):
    Additional CSS classes to apply to the Tabs. The classes specified
    with this prop will be applied to the NavItem in the tab.

- active_tab_class_name (string; optional):
    Additional CSS classes to apply to the Tabs. The classes specified
    with this prop will be applied to the NavItem in the tab when it
    is active.

- label_class_name (string; optional):
    Additional CSS classes to apply to the Tabs. The classes specified
    with this prop will be applied to the NavLink in the tab.

- active_label_class_name (string; optional):
    Additional CSS classes to apply to the Tabs. The classes specified
    with this prop will be applied to the NavLink in the tab when it
    is active.

- key (string; optional):
    A unique identifier for the component, used to improve performance
    by React.js while rendering components  See
    https://react.dev/learn/rendering-lists#why-does-react-need-keys
    for more info.

- className (string; optional):
    **DEPRECATED** Use `class_name` instead.  Additional CSS classes
    to apply to the Tabs.

- tabClassName (string; optional):
    **DEPRECATED** Use `tab_class_name` instead  Additional CSS
    classes to apply to the Tabs. The classes specified with this prop
    will be applied to the NavItem in the tab.

- activeTabClassName (string; optional):
    **DEPRECATED** Use `active_tab_class_name` instead  Additional CSS
    classes to apply to the Tabs. The classes specified with this prop
    will be applied to the NavItem in the tab when it is active.

- labelClassName (string; optional):
    **DEPRECATED** Use `label_class_name` instead  Additional CSS
    classes to apply to the Tabs. The classes specified with this prop
    will be applied to the NavLink in the tab.

- activeLabelClassName (string; optional):
    **DEPRECATED** Use `active_label_class_name` instead  Additional
    CSS classes to apply to the Tabs. The classes specified with this
    prop will be applied to the NavLink in the tab when it is active."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    @_explicitize_args
    def __init__(self, children: typing.Optional[typing.Union[str, int, float, ComponentType, typing.Sequence[typing.Union[str, int, float, ComponentType]]]] = ..., id: typing.Optional[typing.Union[str, dict]] = ..., *, label: typing.Optional[str] = ..., tab_id: typing.Optional[str] = ..., disabled: typing.Optional[bool] = ..., style: typing.Optional[typing.Any] = ..., tab_style: typing.Optional[dict] = ..., active_tab_style: typing.Optional[dict] = ..., label_style: typing.Optional[dict] = ..., active_label_style: typing.Optional[dict] = ..., class_name: typing.Optional[str] = ..., tab_class_name: typing.Optional[str] = ..., active_tab_class_name: typing.Optional[str] = ..., label_class_name: typing.Optional[str] = ..., active_label_class_name: typing.Optional[str] = ..., key: typing.Optional[str] = ..., className: typing.Optional[str] = ..., tabClassName: typing.Optional[str] = ..., activeTabClassName: typing.Optional[str] = ..., labelClassName: typing.Optional[str] = ..., activeLabelClassName: typing.Optional[str] = ..., **kwargs) -> None:
        ...
    


