"""
This type stub file was generated by pyright.
"""

import typing
import numbers
from typing_extensions import Literal
from dash.development.base_component import Component, ComponentType, _explicitize_args

class Toast(Component):
    """A Toast component.
Toasts can be used to push messages and notifactions to users. Control visibility of
the toast with the `is_open` prop, or use `duration` to set a timer for
auto-dismissal.

Keyword arguments:

- children (a list of or a singular dash component, string or number; optional):
    The children of the Toast.

- id (string; optional):
    The ID of the Toast.

- is_open (boolean; default True):
    Whether Toast is currently open.

- dismissable (boolean; default False):
    Set to True to add a dismiss button to the header which will close
    the toast on click.

- duration (number; optional):
    Duration in milliseconds after which the Alert dismisses itself.

- n_dismiss (number; default 0):
    An integer that represents the number of times that the dismiss
    button has been clicked on.

- header (a list of or a singular dash component, string or number; optional):
    Text to populate the header with.

- icon (string; optional):
    Add a contextually coloured icon to the header of the toast.
    Options are: \"primary\", \"secondary\", \"success\", \"warning\",
    \"danger\", \"info\", \"light\" or \"dark\".

- color (string; optional):
    Toast color, options: primary, secondary, success, info, warning,
    danger, light, dark. Default: secondary.

- class_name (string; optional):
    Additional CSS classes to apply to the Toast.

- header_style (dict; optional):
    Additional inline CSS styles to apply to the Toast header.

- header_class_name (string; optional):
    Additional CSS classes to apply to the Toast header.

- body_style (dict; optional):
    Additional CSS classes to apply to the Toast body.

- body_class_name (string; optional):
    Additional CSS classes to apply to the Toast body.

- tag (string; optional):
    HTML tag to use for the Toast, default: div.

- persistence (boolean | string | number; optional):
    Used to allow user interactions to be persisted when the page is
    refreshed. See https://dash.plotly.com/persistence for more
    details.

- persisted_props (list of a value equal to: 'is_open's; optional):
    Properties whose user interactions will persist after refreshing
    the component or the page. Since only `value` is allowed this prop
    can normally be ignored.

- persistence_type (a value equal to: 'local', 'session', 'memory'; optional):
    Where persisted user changes will be stored: - memory: only kept
    in memory, reset on page refresh. - local: window.localStorage,
    data is kept after the browser quit. - session:
    window.sessionStorage, data is cleared once the browser quit.

- key (string; optional):
    A unique identifier for the component, used to improve performance
    by React.js while rendering components  See
    https://react.dev/learn/rendering-lists#why-does-react-need-keys
    for more info.

- className (string; optional):
    **DEPRECATED** Use `class_name` instead.  Additional CSS classes
    to apply to the Toast.

- headerClassName (string; optional):
    **DEPRECATED** - use `header_class_name` instead  Additional CSS
    classes to apply to the Toast. The classes specified with this
    prop will be applied to the header of the toast.

- bodyClassName (string; optional):
    **DEPRECATED** - use `body_class_name` instead.  Additional CSS
    classes to apply to the Toast. The classes specified with this
    prop will be applied to the body of the toast."""
    _children_props = ...
    _base_nodes = ...
    _namespace = ...
    _type = ...
    @_explicitize_args
    def __init__(self, children: typing.Optional[typing.Union[str, int, float, ComponentType, typing.Sequence[typing.Union[str, int, float, ComponentType]]]] = ..., id: typing.Optional[typing.Union[str, dict]] = ..., *, is_open: typing.Optional[bool] = ..., dismissable: typing.Optional[bool] = ..., duration: typing.Optional[typing.Union[int, float, numbers.Number]] = ..., n_dismiss: typing.Optional[typing.Union[int, float, numbers.Number]] = ..., header: typing.Optional[typing.Union[str, int, float, ComponentType, typing.Sequence[typing.Union[str, int, float, ComponentType]]]] = ..., icon: typing.Optional[str] = ..., color: typing.Optional[str] = ..., style: typing.Optional[typing.Any] = ..., class_name: typing.Optional[str] = ..., header_style: typing.Optional[dict] = ..., header_class_name: typing.Optional[str] = ..., body_style: typing.Optional[dict] = ..., body_class_name: typing.Optional[str] = ..., tag: typing.Optional[str] = ..., persistence: typing.Optional[typing.Union[bool, str, typing.Union[int, float, numbers.Number]]] = ..., persisted_props: typing.Optional[typing.Sequence[Literal["is_open"]]] = ..., persistence_type: typing.Optional[Literal["local", "session", "memory"]] = ..., key: typing.Optional[str] = ..., className: typing.Optional[str] = ..., headerClassName: typing.Optional[str] = ..., bodyClassName: typing.Optional[str] = ..., **kwargs) -> None:
        ...
    


