"""
This type stub file was generated by pyright.
"""

from dash_bootstrap_components import _components, icons, themes
from dash_bootstrap_components._components import *
from dash_bootstrap_components._components import Table
from dash_bootstrap_components._table import _generate_table_from_df
from dash_bootstrap_components._version import __version__

"""Bootstrap themed components for use in Plotly Dash"""
__all__ = _components.__all__ + ["icons", "themes"]
_js_dist = ...
_css_dist = ...
def __getattr__(name):
    ...

def __dir__(): # -> list[str]:
    ...

